spring.application.name=BurgerTracker
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/burger_schema?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=nasri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


